---
user: admin
group: admin
home_path: /home/{{user}}

sysctl_rules:
  # turn ON filter for IP spoofing
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.conf.all.rp_filter: 1
  # turn ON defense mechanism for SYN flood
  net.ipv4.tcp_syncookies: 1
  # turn OFF ICMP redirection
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  # turn OFF ipv6 support
  net.ipv6.conf.all.disable_ipv6: 1
  net.ipv6.conf.default.disable_ipv6: 1
  net.ipv6.conf.lo.disable_ipv6: 1
  net.ipv6.conf.eth0.disable_ipv6: 1
